
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  labels:
    app: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp-container
        image: sennurmiray/snapshotintegration
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: springapp
  type: NodePort
  ports:
    - nodePort: 30456
      targetPort: 8080
      port: 9898
